# Generated by Django 6.0 on 2025-12-24 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 23, 21, 8, 20, 425206)),
        ),
    ]
