# Generated by Django 6.0 on 2025-12-24 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 23, 21, 18, 51, 670590)),
        ),
    ]
